= Bookbag Template

This repository should be used as a template for creating (converting) lab content to
be used in Bookbag environments. 

== Creating (converting) Lab Content

. Create a new repository using this one as a template (use the green button *Use this template*).

. Define which modules you want to include in your lab.

. List the modules in the `workshop.yaml` file.

. Edit the `modules.yaml` file to specify modules names and transitions.

. Edit the modules Asciidoc files (`workshop/content/*.adoc`).

. Define which variables you are going to use in your lab instructions (e.g. `GUID`, `USERNAME`, etc.).

. Edit the `config.js` file to include those variables from the environment.

. Use those variables in Asciidoc files like this: `{USERNAME}`. 
Avoid mixing environment variables you use in shell commands and variables you use in Asciidoc text.
For example, you might use `${GUID}` in your shell commands--in this case use `{USER_GUID}` in
the text.


== Building the Bookbag Image

There are two ways of building the Bookbag image.

=== Docker build

Just run the `docker build .` command from the project root directory.

NOTE: Podman doesn't work properly on this build yet.

=== Source-2-image build

You'll need to be logged in an OpenShift cluster to use S2I build.

. Create a new OpenShift project.
+
----
$ oc new-project mylab-bookbag
----

. From the lab project's root directory run the following script: 
+
----
$ .workshop/scripts/build-workshop.sh
----
+
The above command will create a Bookbag image in the cluster's internal image registry 
(usually located at `image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}`)

== Deploying the Bookbag image

To deploy a Bookbag with lab instructions on an OpenShift cluster:

. Create a new OpenShift project or use an existing one:
+
----
$ oc new-project bookbag-test
or
$ oc project bookbag-test
----

. Enter the `deploy` directory and use the template like this:
+
----
$ oc process -f bookbag-template.yaml -p IMAGE=quay.io/panni/bookbag-test:0.0.1 -p SUFFIX="004" | oc apply -f -
----
+
* Use the parameter `IMAGE` to specify your Bookbag image. 
It can be located either in your internal OpenShift registry or externally on *quay.io*, for example.
+
* Use the parameter `SUFFIX` to create several separate Bookbags for different users, for example.

. The template creates a dummy ConfigMap with lab parameters.
'''

The code here is derived from https://github.com/openshift-homeroom.
This repository is based on https://github.com/openshift-homeroom/lab-asciidoc-sample

